# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influxdb.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tayamamo <tayamamo@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/22 12:34:42 by tayamamo          #+#    #+#              #
#    Updated: 2021/01/06 02:42:38 by tayamamo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
    tier: influxdb
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
      tier: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
        tier: influxdb
    spec:
      containers:
      - name: influxdb
        image: ft_services/influxdb:latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /tmp/healthcheck.sh
          initialDelaySeconds: 60
          periodSeconds: 10
        env:
        - name: INFLUXDB_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: admin-username
        - name: INFLUXDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: admin-password
        - name: INFLUXDB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: db-name
        - name: INFLUXDB_TELEGRAF_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-username
        - name: INFLUXDB_TELEGRAF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-password
        - name: INFLUXDB_GRAFANA_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: grafana-username
        - name: INFLUXDB_GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: grafana-password
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
          # mountPath: /root/.influxdbv2
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
stringData:
  admin-username: admin
  admin-password: password
  db-name: telegraf_metrics
  telegraf-username: telegraf
  telegraf-password: passwrod
  grafana-username: grafana
  grafana-password: password
