# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tayamamo <tayamamo@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/21 23:55:03 by tayamamo          #+#    #+#              #
#    Updated: 2021/01/06 02:42:31 by tayamamo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  selector:
    app: grafana
    tier: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: grafana
  template:
    metadata:
      labels:
        app: grafana
        tier: grafana
    spec:
      containers:
      - name: grafana
        image: ft_services/grafana:latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /tmp/healthcheck.sh
          initialDelaySeconds: 60
          periodSeconds: 10
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin-password
        - name: INFLUXDB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: db-name
        - name: INFLUXDB_GRAFANA_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: grafana-username
        - name: INFLUXDB_GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: grafana-password
        - name: INFLUXDB_TELEGRAF_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-username
        - name: INFLUXDB_TELEGRAF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-password

---

apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  admin-user: admin
  admin-password: password
