# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tayamamo <tayamamo@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/18 15:48:18 by tayamamo          #+#    #+#              #
#    Updated: 2021/01/02 05:32:57 by tayamamo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  selector:
    app: wordpress
    tier: phpmyadmin
  ports:
    - name: phpmyadmin
      port: 5000
      targetPort: 5000
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: phpmyadmin
  template:
    metadata:
      labels:
        app: wordpress
        tier: phpmyadmin
    spec:
      containers:
      - image: ft_services/phpmyadmin:latest
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000
          name: phpmyadmin
        env:
        - name: INFLUXDB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: db-name
        - name: INFLUXDB_TELEGRAF_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-username
        - name: INFLUXDB_TELEGRAF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-password
