# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    telegraf.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tayamamo <tayamamo@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/23 22:09:34 by tayamamo          #+#    #+#              #
#    Updated: 2021/01/02 05:33:03 by tayamamo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: ft_services/telegraf
        imagePullPolicy: Never
        name: telegraf
        env:
        - name: INFLUXDB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: db-name
        - name: INFLUXDB_TELEGRAF_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-username
        - name: INFLUXDB_TELEGRAF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-password
