{
 "title": "Docker Metrics",
 "tags": [
  "docker",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values with key = \"engine_host\"\t"
   },
   {
    "name": "container",
    "label": "Service",
    "query": "show tag values with key = \"docker.group\" WHERE engine_host =~ /^$host$/ "
   }
  ]
 },
 "panels": [
  {
   "title": "CPU $container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_engine_host]] $container ([[tag_docker.group]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "docker.group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage % for $container",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_docker.group]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "docker.group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage % for $container",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_docker.group]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "docker.group" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_docker.group]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "docker.group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU global usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_docker.group]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "docker.group" ], "type": "tag" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network overview for $host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_docker.group]] OUT",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "docker.group" ], "type": "tag" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT derivative(mean(\"tx_bytes\"), 10s) FROM \"docker_container_net\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"com.docker.swarm.service.name\" fill(null)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "[[tag_docker.group]] IN",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "docker.group" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}