apiVersion: 1

datasources:
  - name: InfluxDB telegraf
    type: influxdb
    access: proxy
    database: ${INFLUXDB_DB_NAME}
    user: ${INFLUXDB_GRAFANA_USERNAME}
    secureJsonData:
      password: ${INFLUXDB_GRAFANA_PASSWORD}
    url: https://influxdb-service:8086
    jsonData:
      httpMode: GET
      tlsSkipVerify: true
    editable: true
