apiVersion: 1

datasources:
  - name: ${DS_INFLUXDB_TELEGRAF}
    type: influxdb
    access: proxy
    database: telegraf_metrics
    url: https://influxdb-service:8086
    jsonData:
      httpMode: GET
      tlsSkipVerify: true
