# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tayamamo <tayamamo@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/19 15:05:18 by tayamamo          #+#    #+#              #
#    Updated: 2020/12/31 10:51:37 by tayamamo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
    protocol: TCP
  - name: ftps-passive00
    port: 21000
    targetPort: 21000
    protocol: TCP
  - name: ftps-passive01
    port: 21001
    targetPort: 21001
    protocol: TCP
  - name: ftps-passive02
    port: 21002
    targetPort: 21002
    protocol: TCP
  - name: ftps-passive03
    port: 21003
    targetPort: 21003
    protocol: TCP
  - name: ftps-passive04
    port: 21004
    targetPort: 21004
    protocol: TCP
  - name: ftps-passive05
    port: 21005
    targetPort: 21005
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft_services/ftps:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
        env:
        - name: ADDRESS
          value: 192.168.49.10
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        - name: FTPS_USER
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: user
        - name: FTPS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: password
        - name: INFLUXDB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: db-name
        - name: INFLUXDB_TELEGRAF_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-username
        - name: INFLUXDB_TELEGRAF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: telegraf-password
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/ftps
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim

---

apiVersion: v1
kind: Secret
metadata:
  name: ftps-secret
stringData:
  user: admin
  password: password
